services:
  - type: web
    name: nobius-website
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: out
    envVars:
      - key: NODE_VERSION
        value: 20
